### ISSUE TITLE
LC can't recover forever when the corresponding node restarted

### ISSUE THREAD

**Issue by llhuii** [kubeedge/sedna#140]
**What happened**:
Following [this incremental example](https://github.com/kubeedge/sedna/tree/main/examples/incremental_learning/helmet_detection), I created an incremental job.
And by adding enough samples, the job had completed the training worker, but when doing eval worker, its corresponding node restarted. 
After a while, the node had returned to ready state, but LC can't recover, and be `CrashLoopBackOff ` forever.
```sh
# kubectl -n sedna get pod
NAME       READY   STATUS             RESTARTS   AGE
lc-7btfp   0/1     CrashLoopBackOff   256        22h
lc-d7wlc   1/1     Running            0          22h
```
LC logs:
```sh
# kubectl -n sedna logs lc-7btfp
I0730 02:06:32.702494       1 server.go:114] manager dataset is started
I0730 02:06:32.702540       1 server.go:114] manager model is started
I0730 02:06:32.702555       1 server.go:114] manager jointinferenceservice is started
I0730 02:06:32.702580       1 server.go:114] manager federatedlearningjob is started
I0730 02:06:32.702584       1 server.go:114] manager incrementallearningjob is started
I0730 02:06:32.702589       1 server.go:114] manager lifelonglearningjob is started
I0730 02:06:32.702686       1 server.go:139] server binds port 9100 successfully
2021/07/30 02:06:32 /code/pkg/localcontroller/db/db.go:52 record not found
[0.118ms] [rows:0] SELECT * FROM `resources` WHERE name = "default/model/deploy-model" AND `resources`.`deleted_at` IS NULL ORDER BY `resources`.`id` LIMIT 1
I0730 02:06:32.707290       1 incrementallearningjob.go:280] incremental job(name=default/incrementallearningjob/helmet-s3) is started
E0730 02:06:32.707316       1 incrementallearningjob.go:314] job(name=default/incrementallearningjob/helmet-s3) complete the Eval task failed, error: failed to sync deploy model, and waiting it: not exists model(name=default/model/deploy-model)
I0730 02:06:32.714974       1 db.go:65] saved resource(name=default/model/deploy-model)

2021/07/30 02:06:32 /code/pkg/localcontroller/db/db.go:52 record not found
[8.483ms] [rows:0] SELECT * FROM `resources` WHERE name = "default/incrementallearningjob/helmet-s3" AND `resources`.`deleted_at` IS NULL ORDER BY `resources`.`id` LIMIT 1
I0730 02:06:32.724151       1 db.go:65] saved resource(name=default/incrementallearningjob/helmet-s3)

2021/07/30 02:06:32 /code/pkg/localcontroller/db/db.go:52 record not found
[33.739ms] [rows:0] SELECT * FROM `resources` WHERE name = "default/dataset/incremental-dataset" AND `resources`.`deleted_at` IS NULL ORDER BY `resources`.`id` LIMIT 1
I0730 02:06:32.744930       1 db.go:65] saved resource(name=default/dataset/incremental-dataset)
I0730 02:06:33.158989       1 dataset.go:186] dataset(name=default/dataset/incremental-dataset) get samples from data source(url=s3://**/train_data.txt) successfully. number of samples: 30
I0730 02:06:33.178968       1 db.go:74] updated resource(name=default/dataset/incremental-dataset)
I0730 02:06:36.284052       1 db.go:74] updated resource(name=default/dataset/incremental-dataset)
I0730 02:06:36.289717       1 db.go:74] updated resource(name=default/model/deploy-model)
I0730 02:06:36.302150       1 db.go:74] updated resource(name=default/incrementallearningjob/helmet-s3)
I0730 02:06:42.707591       1 panic.go:969] incremental learning job(name=default/incrementallearningjob/helmet-s3) is stopped
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x1468cc0]

goroutine 12 [running]:
github.com/kubeedge/sedna/pkg/localcontroller/manager.(*IncrementalJobManager).triggerEvalTask(0xc0002dd400, 0xc00039a000, 0x0, 0x0, 0x15e29e0)
        /code/pkg/localcontroller/manager/incrementallearningjob.go:557 +0x1f0
github.com/kubeedge/sedna/pkg/localcontroller/manager.(*IncrementalJobManager).evalTask(0xc0002dd400, 0xc00039a000, 0x0, 0x0)
        /code/pkg/localcontroller/manager/incrementallearningjob.go:199 +0x190
github.com/kubeedge/sedna/pkg/localcontroller/manager.(*IncrementalJobManager).startJob(0xc0002dd400, 0xc00034c780, 0x28)
        /code/pkg/localcontroller/manager/incrementallearningjob.go:307 +0x6a8
created by github.com/kubeedge/sedna/pkg/localcontroller/manager.(*IncrementalJobManager).Insert
        /code/pkg/localcontroller/manager/incrementallearningjob.go:348 +0x435
```

**What you expected to happen**:
LC should recover after node is ready.

**How to reproduce it (as minimally and precisely as possible)**:
I configure the dataset, train/eval workers at [a same node](https://github.com/kubeedge/sedna/tree/main/examples/incremental_learning/helmet_detection#create-incremental-job), deploy worker at another node.

**Anything else we need to know?**:

**Environment**:
<details><summary>Sedna Version</summary>

```console
$ kubectl get -n sedna deploy gm -o jsonpath='{.spec.template.spec.containers[0].image}'
# paste output here
kubeedge/sedna-gm:v0.3.0

$ kubectl get -n sedna ds lc -o jsonpath='{.spec.template.spec.containers[0].image}'
# paste output here
kubeedge/sedna-lc:v0.3.0
```

</details>

<details><summary>Kubernets Version</summary>

```console
$ kubectl version
# paste output here
```

</details>

<details><summary>KubeEdge Version</summary>

```console
$ cloudcore --version
# paste output here

$ edgecore --version
# paste output here
```

</details>

**CloudSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**EdgeSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**Comment by llhuii** [comment]
fixed by #152
/close
