### ISSUE TITLE
bug from image "sedna-example-joint-inference-helmet-detection-big:v0.4.3"

### ISSUE THREAD

**Issue by zz952332446** [kubeedge/sedna#289]
I am deploying Example1：[Using Joint Inference Service in Helmet Detection Scenario](https://github.com/kubeedge/sedna/blob/main/examples/joint_inference/helmet_detection_inference/README.md).

**Comment by JoeyHwong-gk** [comment]
Hi @zz952332446 . This is a known issue with `uvicorn` that `sedna` have investigated.  The Ownner has provided fix PR about it in #240 .

**Comment by zz952332446** [comment]
> Hi @zz952332446 . This is a known issue with `uvicorn` that `sedna` have investigated. The Ownner has provided fix PR about it in #240 .

hello, I have tried `uvicorn~=0.14.0`, but the problem still exists
I use `build_image.sh` to build the image, and then `docker run -id ` to start the container

![image](https://user-images.githubusercontent.com/34162360/159648329-1a2fbc94-9f6c-4b57-9773-7f71a7f71c79.png)

![image](https://user-images.githubusercontent.com/34162360/159648376-631900ff-4170-427a-8672-c9368a850959.png)

**Comment by JoeyHwong-gk** [comment]
This problem occurs because the path of big model doesn't  injected into the container, in your case, pass the variable [MODEL_URL] to the container will be solved.
It's recommend that deployment service with k8s, follow [here](https://github.com/kubeedge/sedna/tree/main/examples/joint_inference/helmet_detection_inference#create-joint-inference-service) for more details.

**Comment by 916264367** [comment]
I also encountered the same problem. How did you solve it?

**Comment by 916264367** [comment]
> 我正在部署 Example1：[在头盔检测场景中使用联合推理服务](https://github.com/kubeedge/sedna/blob/main/examples/joint_inference/helmet_detection_inference/README.md)。
> 
> edge还可以，但是master有个问题：container `k8s_big-model_helmet-detection-inference-example-cloud`can't up
> 
> ![图片](https://user-images.githubusercontent.com/34162360/159486040-c6646723-861e-49df-815f-ad4920a92177.png)
> 
> 容器`k8s_big-model_helmet-detection-inference-example-cloud`的日志如下：
> 
> ```
> [2022-03-22 12:44:24,480] base.py(79) [INFO] - Start sedna server over http://10.244.0.10:5000
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.6/threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/uvicorn/server.py", line 69, in run
>     return asyncio.get_event_loop().run_until_complete(self.serve(sockets=sockets))
>   File "/usr/lib/python3.6/asyncio/events.py", line 694, in get_event_loop
>     return get_event_loop_policy().get_event_loop()
>   File "/usr/lib/python3.6/asyncio/events.py", line 602, in get_event_loop
>     % threading.current_thread().name)
> RuntimeError: There is no current event loop in thread 'Thread-1'.
> ```
> 
> 我使用来自 dockerhub 的图像
> 
> ```
> docker pull kubeedge/sedna-example-joint-inference-helmet-detection-big:v0.4.3
> ```

I also encountered the same problem. How did you solve it?

**Comment by zz952332446** [comment]
> > 我正在部署 Example1：[在头盔检测场景中使用联合推理服务](https://github.com/kubeedge/sedna/blob/main/examples/joint_inference/helmet_detection_inference/README.md)。
> > edge还可以，但是master有个问题：container `k8s_big-model_helmet-detection-inference-example-cloud`can't up
> > ![图片](https://user-images.githubusercontent.com/34162360/159486040-c6646723-861e-49df-815f-ad4920a92177.png)
> > 容器`k8s_big-model_helmet-detection-inference-example-cloud`的日志如下：
> > ```
> > [2022-03-22 12:44:24,480] base.py(79) [INFO] - Start sedna server over http://10.244.0.10:5000
> > Exception in thread Thread-1:
> > Traceback (most recent call last):
> >   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
> >     self.run()
> >   File "/usr/lib/python3.6/threading.py", line 864, in run
> >     self._target(*self._args, **self._kwargs)
> >   File "/usr/local/lib/python3.6/dist-packages/uvicorn/server.py", line 69, in run
> >     return asyncio.get_event_loop().run_until_complete(self.serve(sockets=sockets))
> >   File "/usr/lib/python3.6/asyncio/events.py", line 694, in get_event_loop
> >     return get_event_loop_policy().get_event_loop()
> >   File "/usr/lib/python3.6/asyncio/events.py", line 602, in get_event_loop
> >     % threading.current_thread().name)
> > RuntimeError: There is no current event loop in thread 'Thread-1'.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我使用来自 dockerhub 的图像
> > ```
> > docker pull kubeedge/sedna-example-joint-inference-helmet-detection-big:v0.4.3
> > ```
> 
> I also encountered the same problem. How did you solve it?

lib/requirements.txt最后应该是 `uvicorn~=0.14.0`，dockerhub上的v0.4.3镜像这里没有改，有问题
我是自己本地通过dockerfile build生成的，再通过k8s部署deployment就不会报错~

**Comment by 916264367** [comment]
> > > 我正在部署Example1：
> > > 在头盔检测场景中[使用联合推理服务](https://github.com/kubeedge/sedna/blob/main/examples/joint_inference/helmet_detection_inference/README.md)。`k8s_big-model_helmet-detection-inference-example-cloud`
> > > ![图片](https://user-images.githubusercontent.com/34162360/159486040-c6646723-861e-49df-815f-ad4920a92177.png)`k8s_big-model_helmet-detection-inference-example-cloud`
> > > ```
> > > [2022-03-22 12:44:24,480] base.py(79) [INFO] - Start sedna server over http://10.244.0.10:5000
> > > Exception in thread Thread-1:
> > > Traceback (most recent call last):
> > >   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
> > >     self.run()
> > >   File "/usr/lib/python3.6/threading.py", line 864, in run
> > >     self._target(*self._args, **self._kwargs)
> > >   File "/usr/local/lib/python3.6/dist-packages/uvicorn/server.py", line 69, in run
> > >     return asyncio.get_event_loop().run_until_complete(self.serve(sockets=sockets))
> > >   File "/usr/lib/python3.6/asyncio/events.py", line 694, in get_event_loop
> > >     return get_event_loop_policy().get_event_loop()
> > >   File "/usr/lib/python3.6/asyncio/events.py", line 602, in get_event_loop
> > >     % threading.current_thread().name)
> > > RuntimeError: There is no current event loop in thread 'Thread-1'.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我使用来自 dockerhub 的图像
> > > ```
> > > docker pull kubeedge/sedna-example-joint-inference-helmet-detection-big:v0.4.3
> > > ```
> > 
> > 
> > 我也遇到了同样的问题。你是怎么解决的？
> 
> lib/requirements.txt最后应该是`uvicorn~=0.14.0`，dockerhub上的v0.4.3镜像这里没有修改，有问题 我是自己本地通过dockerfile build生成的，再通过k8s部署就不会报部署了~

hello, it's not work. I've fixed uvicon. `uvicorn~=0.14.0`.
![image](https://user-images.githubusercontent.com/51771785/160377076-fa944b1a-cb52-4bdf-8a6d-c8ec41dbca14.png)
When the video is not playing, the pod is running
![image](https://user-images.githubusercontent.com/51771785/160377906-ed7b0ff1-9809-4848-9cbc-6416222bfc0a.png)
But, When I execute `ffmpeg -re -i /data/video/video.mp4 -vcodec libx264 -f rtsp rtsp://localhost/video`, 
![image](https://user-images.githubusercontent.com/51771785/160378253-3af308a2-5005-482d-b183-022b63bf6768.png)
I check the logs of the pod:
![image](https://user-images.githubusercontent.com/51771785/160378557-b2b3aefb-2c64-4a0b-8a69-9b042553d8a8.png)
I don't know why it's the same mistake

**Comment by JoeyHwong-gk** [comment]
> uvicon

After pulling the lastest commits, please rerun `sedna/examples/build_image.sh` to ensure that the local docker image has been replaced.

**Comment by yxlbetter** [comment]
Hello, I also encountered a similar problem, but the container of my small model CrashBackOff at the beginning of running, and I cannot print logs through "kubectl logs", and connect refused will be displayed, can you tell me how to solve it?
