### ISSUE TITLE
kb v0.5.0 is in CrashLoopBackOff status

### ISSUE THREAD

**Issue by hey-kong** [kubeedge/sedna#320]
**What happened**:
kb is in CrashLoopBackOff status

**What you expected to happen**:
kb is in Running status

**Anything else we need to know?**:
kb log:
```
Traceback (most recent call last):
  File "/code/lib/sedna/service/run_kb.py", line 18, in <module>
    from sedna.service.server.knowledgeBase.model import init_db
  File "/code/lib/sedna/__init__.py", line 16, in <module>
    import sedna.algorithms
  File "/code/lib/sedna/algorithms/__init__.py", line 19, in <module>
    from . import optical_flow
  File "/code/lib/sedna/algorithms/optical_flow/__init__.py", line 19, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
```

**Comment by JoeyHwong-gk** [comment]
Thanks for reporting, It seems due to a lack of dependency. Would you like to contribute the pull request yourself?
