### ISSUE TITLE
dog-croissants-classification train-worker error and keep restarting

### ISSUE THREAD

**Issue by xinzongyan** [kubeedge/sedna#386]
**What happened**:
dog-croissants-classification train-worker error and keep restarting in incremental-learning example 

[root@board2 ~]# docker logs -f k8s_train-worker_incremental-learning-dog-croissants-classification-train-fvsfk_default_3cacec7e-3e19-4d67-ba3e-e94545c812b5_1
num_parallel_workers=2
train_dataset_url /home/data/sedna/incremental_learning/dog_croissants_classification/dataset/data/dog_croissants/train
valid_dataset_urlL : /home/data/sedna/incremental_learning/dog_croissants_classification/dataset/data/dog_croissants/val
Traceback (most recent call last):
  File "train.py", line 67, in <module>
    main()
  File "train.py", line 52, in main
    num_parallel_workers=num_parallel_workers)
  File "/home/work/dataset.py", line 32, in parse
    vision.RandomCropDecodeResize(image_shape, scale=(0.08, 1.0), ratio=(0.75, 1.333)),
AttributeError: module 'mindspore.dataset.vision' has no attribute 'RandomCropDecodeResize'

**What you expected to happen**:
trainning successful

**How to reproduce it (as minimally and precisely as possible)**:
Use the main branch to compile the image，it's easy to reproduce it

**Anything else we need to know?**:
It seems RandomCropDecodeResize used in mindspore/mindspore-cpu:1.9.0 ,
and import 1.7.1 in incremental-learning-dog-croissants-classification.Dockerfile like this：
FROM mindspore/mindspore-cpu:1.7.1 

**Environment**:
<details><summary>Sedna Version</summary>

```console
$ kubectl get -n sedna deploy gm -o jsonpath='{.spec.template.spec.containers[0].image}'
# paste output here
kubeedge/sedna-gm:v0.5.1

$ kubectl get -n sedna ds lc -o jsonpath='{.spec.template.spec.containers[0].image}'
# paste output here
```
kubeedge/sedna-lc:v0.5.1
</details>

<details><summary>Kubernets Version</summary>

```console
$ kubectl version
# paste output here
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T17:57:25Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

</details>

<details><summary>KubeEdge Version</summary>

```console
$ cloudcore --version
# paste output here
 Version: v1.12.1

$ edgecore --version
# paste output here
```
 Version: v1.12.1
</details>

**Comment by qimiao1** [comment]
hello ,do you solve it ? @
